---
- name: Install basic packages
  apt: name={{ item }} state=present update_cache=yes
  with_items: common_packages
  tags: ['common']

- name: Install host-specific packages
  apt: name={{ item }} state=present
  with_items: extra_packages
  when: extra_packages is defined
  tags: ['common']

- name: Update all packages
  apt: upgrade=dist
  tags: ['common']
