---
- name: Install basic packages
  yum: name={{ item }} state=present
  with_items: common_packages_yum
  tags: ['common']

- name: Install host-specific packages
  yum: name={{ item }} state=present
  with_items: host_packages
  when: host_packages is defined
  tags: ['common']

- name: Update all packages
  yum: name=* state=latest
  tags: ['common']
